# permissions for end users to edit ratelimits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ratelimit-editor-role
rules:
- apiGroups:
  - networking.softonic.io
  resources:
  - ratelimits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.softonic.io
  resources:
  - ratelimits/status
  verbs:
  - get
