// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package istio_v1alpha3

import (
	"encoding/json"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMatch) DeepCopyInto(out *ClusterMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMatch.
func (in *ClusterMatch) DeepCopy() *ClusterMatch {
	if in == nil {
		return nil
	}
	out := new(ClusterMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyConfigObjectMatch) DeepCopyInto(out *EnvoyConfigObjectMatch) {
	*out = *in
	in.Proxy.DeepCopyInto(&out.Proxy)
	if in.Listener != nil {
		in, out := &in.Listener, &out.Listener
		*out = new(ListenerMatch)
		**out = **in
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(ClusterMatch)
		**out = **in
	}
	if in.RouteConfiguration != nil {
		in, out := &in.RouteConfiguration, &out.RouteConfiguration
		*out = new(RouteConfigurationMatch)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyConfigObjectMatch.
func (in *EnvoyConfigObjectMatch) DeepCopy() *EnvoyConfigObjectMatch {
	if in == nil {
		return nil
	}
	out := new(EnvoyConfigObjectMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyConfigObjectMatch_Listener) DeepCopyInto(out *EnvoyConfigObjectMatch_Listener) {
	*out = *in
	out.Listener = in.Listener
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyConfigObjectMatch_Listener.
func (in *EnvoyConfigObjectMatch_Listener) DeepCopy() *EnvoyConfigObjectMatch_Listener {
	if in == nil {
		return nil
	}
	out := new(EnvoyConfigObjectMatch_Listener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyConfigObjectPatch) DeepCopyInto(out *EnvoyConfigObjectPatch) {
	*out = *in
	in.Match.DeepCopyInto(&out.Match)
	in.Patch.DeepCopyInto(&out.Patch)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyConfigObjectPatch.
func (in *EnvoyConfigObjectPatch) DeepCopy() *EnvoyConfigObjectPatch {
	if in == nil {
		return nil
	}
	out := new(EnvoyConfigObjectPatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyFilter) DeepCopyInto(out *EnvoyFilter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyFilter.
func (in *EnvoyFilter) DeepCopy() *EnvoyFilter {
	if in == nil {
		return nil
	}
	out := new(EnvoyFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvoyFilter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyFilterList) DeepCopyInto(out *EnvoyFilterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EnvoyFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyFilterList.
func (in *EnvoyFilterList) DeepCopy() *EnvoyFilterList {
	if in == nil {
		return nil
	}
	out := new(EnvoyFilterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvoyFilterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyFilterSpec) DeepCopyInto(out *EnvoyFilterSpec) {
	*out = *in
	in.WorkloadSelector.DeepCopyInto(&out.WorkloadSelector)
	if in.ConfigPatches != nil {
		in, out := &in.ConfigPatches, &out.ConfigPatches
		*out = make([]EnvoyConfigObjectPatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyFilterSpec.
func (in *EnvoyFilterSpec) DeepCopy() *EnvoyFilterSpec {
	if in == nil {
		return nil
	}
	out := new(EnvoyFilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyFilterStatus) DeepCopyInto(out *EnvoyFilterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyFilterStatus.
func (in *EnvoyFilterStatus) DeepCopy() *EnvoyFilterStatus {
	if in == nil {
		return nil
	}
	out := new(EnvoyFilterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerMatch) DeepCopyInto(out *ListenerMatch) {
	*out = *in
	out.FilterChain = in.FilterChain
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerMatch.
func (in *ListenerMatch) DeepCopy() *ListenerMatch {
	if in == nil {
		return nil
	}
	out := new(ListenerMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerMatch_FilterChainMatch) DeepCopyInto(out *ListenerMatch_FilterChainMatch) {
	*out = *in
	out.Filter = in.Filter
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerMatch_FilterChainMatch.
func (in *ListenerMatch_FilterChainMatch) DeepCopy() *ListenerMatch_FilterChainMatch {
	if in == nil {
		return nil
	}
	out := new(ListenerMatch_FilterChainMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerMatch_FilterMatch) DeepCopyInto(out *ListenerMatch_FilterMatch) {
	*out = *in
	out.SubFilter = in.SubFilter
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerMatch_FilterMatch.
func (in *ListenerMatch_FilterMatch) DeepCopy() *ListenerMatch_FilterMatch {
	if in == nil {
		return nil
	}
	out := new(ListenerMatch_FilterMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerMatch_SubFilterMatch) DeepCopyInto(out *ListenerMatch_SubFilterMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerMatch_SubFilterMatch.
func (in *ListenerMatch_SubFilterMatch) DeepCopy() *ListenerMatch_SubFilterMatch {
	if in == nil {
		return nil
	}
	out := new(ListenerMatch_SubFilterMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Patch) DeepCopyInto(out *Patch) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Patch.
func (in *Patch) DeepCopy() *Patch {
	if in == nil {
		return nil
	}
	out := new(Patch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyMatch) DeepCopyInto(out *ProxyMatch) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyMatch.
func (in *ProxyMatch) DeepCopy() *ProxyMatch {
	if in == nil {
		return nil
	}
	out := new(ProxyMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteConfiguration) DeepCopyInto(out *RouteConfiguration) {
	*out = *in
	out.RouteConfiguration = in.RouteConfiguration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteConfiguration.
func (in *RouteConfiguration) DeepCopy() *RouteConfiguration {
	if in == nil {
		return nil
	}
	out := new(RouteConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteConfigurationMatch) DeepCopyInto(out *RouteConfigurationMatch) {
	*out = *in
	out.Vhost = in.Vhost
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteConfigurationMatch.
func (in *RouteConfigurationMatch) DeepCopy() *RouteConfigurationMatch {
	if in == nil {
		return nil
	}
	out := new(RouteConfigurationMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteConfigurationMatch_RouteMatch) DeepCopyInto(out *RouteConfigurationMatch_RouteMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteConfigurationMatch_RouteMatch.
func (in *RouteConfigurationMatch_RouteMatch) DeepCopy() *RouteConfigurationMatch_RouteMatch {
	if in == nil {
		return nil
	}
	out := new(RouteConfigurationMatch_RouteMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteConfigurationMatch_VirtualHostMatch) DeepCopyInto(out *RouteConfigurationMatch_VirtualHostMatch) {
	*out = *in
	out.Route = in.Route
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteConfigurationMatch_VirtualHostMatch.
func (in *RouteConfigurationMatch_VirtualHostMatch) DeepCopy() *RouteConfigurationMatch_VirtualHostMatch {
	if in == nil {
		return nil
	}
	out := new(RouteConfigurationMatch_VirtualHostMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSelector) DeepCopyInto(out *WorkloadSelector) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSelector.
func (in *WorkloadSelector) DeepCopy() *WorkloadSelector {
	if in == nil {
		return nil
	}
	out := new(WorkloadSelector)
	in.DeepCopyInto(out)
	return out
}
